### ISSUE TITLE
Is it possible to reopen an old session?

### ISSUE THREAD

**Issue by brunobmello25** [Aaronik/GPTModels.nvim#5]
Sometimes I'm working on two separate conversations in GptModelsChat. For example, I'm writing my college final paper with the help of GPT using a conversation for content, and another separate conversation for LaTeX specific questions. I'd like to keep these two contexts separate to avoid confusion, and I'd also like to get back to them from time to time, after working on other conversations with GPT. Is this currently possible or is it a planned feature in this plugin?

**Comment by aaronik** [comment]
Hah I was wondering when this question was going to first appear!

As you clearly know, GPTModels doesn't currently have any session saving functionality. I've avoided adding this because for my particular workflow, it doesn't really add anything, and session management is a big addition to the code, so it didn't seem worthwhile for me.

But I figured at some point somebody might have a use case that would make it nice.

Unfortunately I don't have any immediate plans to add session management. But there might be another way to achieve your needs. Have you tried having two neovim sessions open on the same file(s), maybe in different terminal tabs or something, and switching between them? Would that be an acceptable workaround?

---

BEGIN SANCTIMONIOUS SOAPBOX -- feel free to just not even read the rest of this comment

---

You live your life just as you see fit. But I do want to just say a thing. As a person who is getting a little older, having some grey hairs in a few places on the dome, when I went to college, I didn't have AIs. I didn't even have youtube - it was around but not full of content like it is now. I believe AIs are an extraordinarily powerful tool that can help humans advance their knowledge in profound ways. But they also can help us avoid learning, if that's how we use them. Growth of all kinds, including intellectual growth, is difficult, it's just hard to do, it takes energy and we seek low energy states, so it comes with discomfort. But it's profoundly rewarding. For all I know, you're using these to better yourself in the best of ways. But just in case you're not, consider this a plea on behalf of your future self to use AI to better yourself rather than take a load off your homework :)

Rant over, hope you didn't read it :P

**Comment by brunobmello25** [comment]
Yeah I've been doing that! I'm currently using tmux and opening a session for each conversation, so that's not at all a blocker to my usage. Was just wondering if there were any plans, but that's totally fine if it's not planned!

---

> You live your life just as you see fit. But I do want to just say a thing. As a person who is getting a little older, having some grey hairs in a few places on the dome, when I went to college, I didn't have AIs. I didn't even have youtube - it was around but not full of content like it is now. I believe AIs are an extraordinarily powerful tool that can help humans advance their knowledge in profound ways. But they also can help us avoid learning, if that's how we use them. Growth of all kinds, including intellectual growth, is difficult, it's just hard to do, it takes energy and we seek low energy states, so it comes with discomfort. But it's profoundly rewarding. For all I know, you're using these to better yourself in the best of ways. But just in case you're not, consider this a plea on behalf of your future self to use AI to better yourself rather than take a load off your homework :)

That's an absolutely great point, thanks for calling it out <3

Indeed, I'm currently using it as a "second hand", making it easier to write some complicated LaTeX boilerplate and sometimes consulting with what I'm currently writing, but indeed I have already fallen into the trap of trying to delegate my thinking to AI in the past, and let me tell you it did not went great hahaha at the end I had something working but I felt I didn't learn anything, so I ended up just redoing the whole thing in order to properly learn

Since then, I've made a deal with myself to never let these tools replace my mind and it's thinking process, just be complementary to it. I do agree that it's important.

**Comment by aaronik** [comment]
> Yeah I've been doing that! I'm currently using tmux and opening a session for each conversation, so that's not at all a blocker to my usage.

Awesome possum!

> That's an absolutely great point, thanks for calling it out <3
> 
> Indeed, I'm currently using it as a "second hand", making it easier to write some complicated LaTeX boilerplate and sometimes consulting with what I'm currently writing, but indeed I have already fallen into the trap of trying to delegate my thinking to AI in the past, and let me tell you it did not went great hahaha at the end I had something working but I felt I didn't learn anything, so I ended up just redoing the whole thing in order to properly learn
> 
> Since then, I've made a deal with myself to never let these tools replace my mind and it's thinking process, just be complementary to it. I do agree that it's important.

Excellent it sounds like you're in peak form with it. Nice! And thanks for listening to my soap box lol

---

I'm gonna close this as a won't fix kinda thing, but actually I will have my ears open about if anyone else is really wanting this feature. Not promising to do it any time soon, but the code is such that it wouldn't be impossible. So if there's enough demand and we can't find a good enough workaround, then maybe it'll be something I put some time into.

**Comment by brunobmello25** [comment]
Sounds good! I'll also see if I can come up with something once I've got some free time, and if I can then I'll open a PR

**Comment by aaronik** [comment]
Ok but do keep in mind - I'm going to be very particular about the code for this plugin. It'll have to be just about impeccable, especially if there's anything about saving to disk. But of course that only counts towards upstream merges. I'm open to them but I'll have to be convinced.
